script: 
  - lscpu
  - free -h
  - ifconfig
  - sudo cat /etc/docker/daemon.json
  - echo '{"mtu":1450}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - ifconfig
  - sudo cat /etc/docker/daemon.json
  - docker network inspect bridge
  - sudo cat /lib/systemd/system/docker.service
  - curl https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le/current_repodata.json > log.txt
  - curl http://storage.googleapis.com/kubernetes-release/release/v1.14.2/bin/linux/ppc64le/kubectl > log1.txt
  - docker run -t centos:7 bash -c 'curl https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le/current_repodata.json > log.txt; curl http://storage.googleapis.com/kubernetes-release/release/v1.14.2/bin/linux/ppc64le/kubectl > log1.txt'
 
service: docker

jobs:
  include:
    - os: linux-ppc64le
    - arch: ppc64le
  
  
