jobs:
  include:
    - name: Network test
      os: linux-ppc64le
      script:
        - ifconfig
        - ping -c 4 google.com
        - curl https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le/current_repodata.json > log.txt
        - docker run -t centos:7 bash -c 'curl https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le/current_repodata.json > log.txt; curl http://storage.googleapis.com/kubernetes-release/release/v1.14.2/bin/linux/ppc64le/kubectl > log1.txt'
        
    - name: Docker test
      os: linux-ppc64le
      service: docker
      script:
        - docker version
        - sudo cat /etc/docker/daemon.json
        - systemctl status docker --no-pager -l
        - docker pull alpine:latest
        - docker run -t --rm alpine:latest uname -a
        
     - name: Apt install test
       os: linux-ppc64le
       addons:
        apt:
          update: true
          packages:
            - cmake
            - time
       script:
        - sudo apt update -y
        - sudo apt install -y linux-headers-$(uname -r)

  
